"""TV-specific queries."""

PROGRAM_HISTORY_PIVOT = """
SELECT
  EQMT_NAME,
  BASE_PROGRAM AS Program,
  SUM(CASE WHEN WorkDate = CAST(GETDATE() AS DATE) THEN WorkedPcb ELSE 0 END) AS Danas,
  SUM(CASE WHEN WorkDate = DATEADD(DAY, -1, CAST(GETDATE() AS DATE)) THEN WorkedPcb ELSE 0 END) AS Juce,
  SUM(CASE WHEN WorkDate = DATEADD(DAY, -2, CAST(GETDATE() AS DATE)) THEN WorkedPcb ELSE 0 END) AS "Pre 2d",
  SUM(CASE WHEN WorkDate = DATEADD(DAY, -3, CAST(GETDATE() AS DATE)) THEN WorkedPcb ELSE 0 END) AS "Pre 3d",
  SUM(CASE WHEN WorkDate = DATEADD(DAY, -4, CAST(GETDATE() AS DATE)) THEN WorkedPcb ELSE 0 END) AS "Pre 4d",
  SUM(CASE WHEN WorkDate = DATEADD(DAY, -5, CAST(GETDATE() AS DATE)) THEN WorkedPcb ELSE 0 END) AS "Pre 5d",
  SUM(CASE WHEN WorkDate = DATEADD(DAY, -6, CAST(GETDATE() AS DATE)) THEN WorkedPcb ELSE 0 END) AS "Pre 6d",
  SUM(WorkedPcb) AS Ukupno
FROM VW_PLACE_COUNT
WHERE WorkDate BETWEEN DATEADD(DAY, -7, GETDATE()) AND GETDATE()
GROUP BY EQMT_NAME, BASE_PROGRAM
ORDER BY EQMT_NAME, Ukupno DESC;
"""
